# Generated by Django 5.1.3 on 2024-11-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fabricante', models.CharField(max_length=100, verbose_name='null=False')),
                ('criado_em', models.DateTimeField()),
                ('alterado_em', models.DateTimeField()),
            ],
        ),
    ]
