# Generated by Django 5.1.3 on 2024-11-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produto_image_alter_categoria_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='msgpromocao',
            field=models.CharField(blank='True', max_length=100, null=True),
        ),
    ]
